apiVersion: apps/v1
kind: Deployment
metadata:
  name: titreminexcel-backend
  labels:
    app: titreminexcel-backend
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: titreminexcel-backend
  template:
    metadata:
      labels:
        app: titreminexcel-backend
    spec:
      containers:
        - name: backend
          image: {{ .Values.backend.image }}
          imagePullPolicy: Always
          ports:
            - containerPort: {{ .Values.backend.port }}
          envFrom:
            - configMapRef:
                name: titreminexcel-config
            - secretRef:
                name: titreminexcel-secret
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: {{ .Values.backend.port }}
            initialDelaySeconds: 20
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: {{ .Values.backend.port }}
            initialDelaySeconds: 10
            periodSeconds: 5
