replicaCount: 1

backend:
  image: younesen/titreminexcel-backend:latest
  port: 9091

frontend:
  image: younesen/titreminexcel-frontend:latest
  port: 80

service:
  type: NodePort
  frontendNodePort: 31337
  backendNodePort: 31338

ingress:
  enabled: true
  className: "nginx"
  annotations: {}
  hosts:
    - host: titreminexcel.local
      paths:
        - path: /
          pathType: Prefix
        - path: /api
          pathType: Prefix

httpRoute:
  enabled: false
