replicaCount: 3
backend:
  image: younesen/titreminexcel-backend:prod
  port: 9091
frontend:
  image: younesen/titreminexcel-frontend:prod
  port: 80
service:
  type: NodePort
  frontendNodePort: 31337
  backendNodePort: 31338
ingress:
  enabled: true
  hosts:
    - host: titreminexcel.local
      paths:
        - path: /
          pathType: Prefix
