replicaCount: 1

backend:
  image: titreminexcel-backend:local
  port: 9091

frontend:
  image: titreminexcel-frontend:local
  port: 80

service:
  type: NodePort
  frontendNodePort: 31337
  backendNodePort: 31338

ingress:
  enabled: false
