replicaCount: 1
backend:
  image: younesen/titreminexcel-backend:latest
  port: 9091
frontend:
  image: younesen/titreminexcel-frontend:latest
  port: 80
service:
  type: NodePort
  frontendNodePort: 31317
  backendNodePort: 31318
ingress:
  enabled: true
  hosts:
    - host: titreminexcel-dev.local
      paths:
        - path: /
          pathType: Prefix
