replicaCount: 1

versionTag: "1.0.0"

backend:
  image: "younesen/titreminexcel-backend:${VERSION_TAG}
  port: 9091

frontend:
  image: "younesen/titreminexcel-frontend:${VERSION_TAG}
  port: 80

service:
  type: NodePort
  frontendNodePort: 31337
  backendNodePort: 31338

ingress:
  enabled: true
  className: "nginx"
  annotations: {}
  hosts:
    - host: titreminexcel.local
      paths:
        - path: /
          pathType: Prefix
        - path: /api
          pathType: Prefix

httpRoute:
  enabled: false
