apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: titreminexcel-environments
spec:
  generators:
    - list:
        elements:
          - name: dev
            namespace: titreminexcel-dev
            valuesFile: values-dev.yaml
          - name: staging
            namespace: titreminexcel-staging
            valuesFile: values-staging.yaml
          - name: prod
            namespace: titreminexcel-prod
            valuesFile: values-prod.yaml
  template:
    metadata:
      name: titreminexcel-{{name}}
    spec:
      project: default
      source:
        repoURL: https://github.com/younesen/titreminexcel.git
        targetRevision: main
        path: helm-charts/titreminexcel
        helm:
          valueFiles:
            - "{{valuesFile}}"
      destination:
        server: https://kubernetes.default.svc
        namespace: "{{namespace}}"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
